plugins {
    id 'java'
    id("org.jetbrains.intellij.platform") version "2.1.0"
    id 'org.jetbrains.kotlin.jvm' version '2.2.0'
}

group 'com.dongqing.plugin'
version '5.2'

repositories {
    mavenCentral()
    
    intellijPlatform {
        defaultRepositories()
    }
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib"
    
    intellijPlatform {
        // 使用 2024.3 版本以避免 2025.2.5 的依赖解析问题

        create("IC", "2024.3.2")
        // Add necessary plugin dependencies for compilation here
        bundledPlugin("com.intellij.java")
        bundledPlugin("com.intellij.gradle")
        bundledPlugin("org.jetbrains.kotlin")

        // Add instrumentation tools required for build
        instrumentationTools()
    }
}

intellijPlatform {
    pluginConfiguration {
        ideaVersion {
            sinceBuild = "243"
            untilBuild = "252.*"
        }
    }
}


patchPluginXml {
    sinceBuild = '252'
    untilBuild = '255.*'
    pluginDescription = """
      1. 【ctrl U】Auto generate findViewById code in activity ,fragment or adapter etc,and support Kotlin or Java.<br>
      2. 【ctrl M】Merge findViewById or  butterknife to ViewBinding.<br>
      自动生成activity、fragment、adapter等findViewById代码，支持Kotlin和Java(快捷键ctrl U).<br>
      替换findViewById、ButterKnife为ViewBinding(快捷键ctrl M).<br>
     """
    changeNotes = """
      5.2 Adapt to IntelliJ IDEA 2025.2 and Kotlin K2.<br>
      5.1 Support merge ButterKnife to ViewBinding(ButterKnife替换为ViewBinding).<br>
      5.0 Merge findViewById to ViewBinding(一键替换为ViewBinding).<br>
      4.0 Support ButterKnife(支持黄油刀).<br>
      3.2 Add xml generate adapter(支持xml生成Adapter).<br>
      3.1 Add Settings(添加设置).<br>
      2.0 Support BaseAdapter and RecyclerAdapter(支持各种适配器).<br>
      1.1 Support Field Naming Conventions(三种命名选择).<br>
      1.0 Support Activity and Fragment(支持activity与fragment).<br>
    """
}

